platform: x64

clone_folder: c:\gopath\src\github.com\sacloud\terraform-provider-sakuracloud

environment:
  GOPATH: c:\gopath
  GOROOT: c:\go111
  GO111MODULE: on

install:
  - choco install bzr
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;C:\go111\bin;C:\Program Files (x86)\Bazaar\;%PATH%
  - go version
  - go env

init:
  - git config --global core.autocrlf false

test_script:
  - go test -v ./sakuracloud -timeout=30s -parallel=4

build: off
deploy: off
